server:
  host: 0.0.0.0
  port: 3000
openapi:
  title: TruckManager
  description:
  version: 1.0
  tags:
    - Truck
  path: docs
mongodb:
  uri: "mongodb://root:motdepasse@0.0.0.0:27017/truckManager?authSource=admin"
cors:
  origin: "http://localhost:4200"
  methods: "GET,POST,PUT,DELETE,OPTIONS,HEAD"
  allowedHeaders: "Content-Type, Accept"
  exposedHeaders: "Location"
  credentials: false
